-- Add missing countries to jurisdictions table
INSERT INTO public.jurisdictions (code, country, name, parent_code) VALUES
-- Chile (already exists, skipping)
-- Bolivia
('BO', 'BO', 'Bolivia', NULL),
('BO-CH', 'BO', 'Chuquisaca', 'BO'),
('BO-LP', 'BO', 'La Paz', 'BO'),
('BO-CB', 'BO', 'Cochabamba', 'BO'),
('BO-OR', 'BO', 'Oruro', 'BO'),
('BO-PT', 'BO', 'Potosí', 'BO'),
('BO-TJ', 'BO', 'Tarija', 'BO'),
('BO-SC', 'BO', 'Santa Cruz', 'BO'),
('BO-BN', 'BO', 'Beni', 'BO'),
('BO-PD', 'BO', 'Pando', 'BO'),

-- Uruguay (already exists, skipping)

-- Paraguay (already exists, skipping)

-- Peru 
('PE', 'PE', 'Perú', NULL),
('PE-AMA', 'PE', 'Amazonas', 'PE'),
('PE-ANC', 'PE', 'Áncash', 'PE'),
('PE-APU', 'PE', 'Apurímac', 'PE'),
('PE-ARE', 'PE', 'Arequipa', 'PE'),
('PE-AYA', 'PE', 'Ayacucho', 'PE'),
('PE-CAJ', 'PE', 'Cajamarca', 'PE'),
('PE-CAL', 'PE', 'Callao', 'PE'),
('PE-CUS', 'PE', 'Cusco', 'PE'),
('PE-HUV', 'PE', 'Huancavelica', 'PE'),
('PE-HUC', 'PE', 'Huánuco', 'PE'),
('PE-ICA', 'PE', 'Ica', 'PE'),
('PE-JUN', 'PE', 'Junín', 'PE'),
('PE-LAL', 'PE', 'La Libertad', 'PE'),
('PE-LAM', 'PE', 'Lambayeque', 'PE'),
('PE-LIM', 'PE', 'Lima', 'PE'),
('PE-LOR', 'PE', 'Loreto', 'PE'),
('PE-MDD', 'PE', 'Madre de Dios', 'PE'),
('PE-MOQ', 'PE', 'Moquegua', 'PE'),
('PE-PAS', 'PE', 'Pasco', 'PE'),
('PE-PIU', 'PE', 'Piura', 'PE'),
('PE-PUN', 'PE', 'Puno', 'PE'),
('PE-SAM', 'PE', 'San Martín', 'PE'),
('PE-TAC', 'PE', 'Tacna', 'PE'),
('PE-TUM', 'PE', 'Tumbes', 'PE'),
('PE-UCA', 'PE', 'Ucayali', 'PE'),

-- Ecuador
('EC', 'EC', 'Ecuador', NULL),
('EC-A', 'EC', 'Azuay', 'EC'),
('EC-B', 'EC', 'Bolívar', 'EC'),
('EC-F', 'EC', 'Cañar', 'EC'),
('EC-C', 'EC', 'Carchi', 'EC'),
('EC-H', 'EC', 'Chimborazo', 'EC'),
('EC-X', 'EC', 'Cotopaxi', 'EC'),
('EC-O', 'EC', 'El Oro', 'EC'),
('EC-E', 'EC', 'Esmeraldas', 'EC'),
('EC-W', 'EC', 'Galápagos', 'EC'),
('EC-G', 'EC', 'Guayas', 'EC'),
('EC-I', 'EC', 'Imbabura', 'EC'),
('EC-L', 'EC', 'Loja', 'EC'),
('EC-R', 'EC', 'Los Ríos', 'EC'),
('EC-M', 'EC', 'Manabí', 'EC'),
('EC-S', 'EC', 'Morona Santiago', 'EC'),
('EC-N', 'EC', 'Napo', 'EC'),
('EC-D', 'EC', 'Orellana', 'EC'),
('EC-Y', 'EC', 'Pastaza', 'EC'),
('EC-P', 'EC', 'Pichincha', 'EC'),
('EC-SE', 'EC', 'Santa Elena', 'EC'),
('EC-SD', 'EC', 'Santo Domingo', 'EC'),
('EC-U', 'EC', 'Sucumbíos', 'EC'),
('EC-T', 'EC', 'Tungurahua', 'EC'),
('EC-Z', 'EC', 'Zamora Chinchipe', 'EC'),

-- Venezuela
('VE', 'VE', 'Venezuela', NULL),
('VE-Z', 'VE', 'Amazonas', 'VE'),
('VE-B', 'VE', 'Anzoátegui', 'VE'),
('VE-C', 'VE', 'Apure', 'VE'),
('VE-D', 'VE', 'Aragua', 'VE'),
('VE-E', 'VE', 'Barinas', 'VE'),
('VE-F', 'VE', 'Bolívar', 'VE'),
('VE-G', 'VE', 'Carabobo', 'VE'),
('VE-H', 'VE', 'Cojedes', 'VE'),
('VE-Y', 'VE', 'Delta Amacuro', 'VE'),
('VE-W', 'VE', 'Dependencias Federales', 'VE'),
('VE-A', 'VE', 'Distrito Capital', 'VE'),
('VE-I', 'VE', 'Falcón', 'VE'),
('VE-J', 'VE', 'Guárico', 'VE'),
('VE-K', 'VE', 'Lara', 'VE'),
('VE-L', 'VE', 'Mérida', 'VE'),
('VE-M', 'VE', 'Miranda', 'VE'),
('VE-N', 'VE', 'Monagas', 'VE'),
('VE-O', 'VE', 'Nueva Esparta', 'VE'),
('VE-P', 'VE', 'Portuguesa', 'VE'),
('VE-R', 'VE', 'Sucre', 'VE'),
('VE-S', 'VE', 'Táchira', 'VE'),
('VE-T', 'VE', 'Trujillo', 'VE'),
('VE-X', 'VE', 'Vargas', 'VE'),
('VE-U', 'VE', 'Yaracuy', 'VE'),
('VE-V', 'VE', 'Zulia', 'VE'),

-- Mexico
('MX', 'MX', 'México', NULL),
('MX-AGU', 'MX', 'Aguascalientes', 'MX'),
('MX-BCN', 'MX', 'Baja California', 'MX'),
('MX-BCS', 'MX', 'Baja California Sur', 'MX'),
('MX-CAM', 'MX', 'Campeche', 'MX'),
('MX-CHP', 'MX', 'Chiapas', 'MX'),
('MX-CHH', 'MX', 'Chihuahua', 'MX'),
('MX-CMX', 'MX', 'Ciudad de México', 'MX'),
('MX-COA', 'MX', 'Coahuila', 'MX'),
('MX-COL', 'MX', 'Colima', 'MX'),
('MX-DUR', 'MX', 'Durango', 'MX'),
('MX-GUA', 'MX', 'Guanajuato', 'MX'),
('MX-GRO', 'MX', 'Guerrero', 'MX'),
('MX-HID', 'MX', 'Hidalgo', 'MX'),
('MX-JAL', 'MX', 'Jalisco', 'MX'),
('MX-MEX', 'MX', 'México', 'MX'),
('MX-MIC', 'MX', 'Michoacán', 'MX'),
('MX-MOR', 'MX', 'Morelos', 'MX'),
('MX-NAY', 'MX', 'Nayarit', 'MX'),
('MX-NLE', 'MX', 'Nuevo León', 'MX'),
('MX-OAX', 'MX', 'Oaxaca', 'MX'),
('MX-PUE', 'MX', 'Puebla', 'MX'),
('MX-QUE', 'MX', 'Querétaro', 'MX'),
('MX-ROO', 'MX', 'Quintana Roo', 'MX'),
('MX-SLP', 'MX', 'San Luis Potosí', 'MX'),
('MX-SIN', 'MX', 'Sinaloa', 'MX'),
('MX-SON', 'MX', 'Sonora', 'MX'),
('MX-TAB', 'MX', 'Tabasco', 'MX'),
('MX-TAM', 'MX', 'Tamaulipas', 'MX'),
('MX-TLA', 'MX', 'Tlaxcala', 'MX'),
('MX-VER', 'MX', 'Veracruz', 'MX'),
('MX-YUC', 'MX', 'Yucatán', 'MX'),
('MX-ZAC', 'MX', 'Zacatecas', 'MX'),

-- USA
('US', 'US', 'Estados Unidos', NULL),
('US-AL', 'US', 'Alabama', 'US'),
('US-AK', 'US', 'Alaska', 'US'),
('US-AZ', 'US', 'Arizona', 'US'),
('US-AR', 'US', 'Arkansas', 'US'),
('US-CA', 'US', 'California', 'US'),
('US-CO', 'US', 'Colorado', 'US'),
('US-CT', 'US', 'Connecticut', 'US'),
('US-DE', 'US', 'Delaware', 'US'),
('US-FL', 'US', 'Florida', 'US'),
('US-GA', 'US', 'Georgia', 'US'),
('US-HI', 'US', 'Hawaii', 'US'),
('US-ID', 'US', 'Idaho', 'US'),
('US-IL', 'US', 'Illinois', 'US'),
('US-IN', 'US', 'Indiana', 'US'),
('US-IA', 'US', 'Iowa', 'US'),
('US-KS', 'US', 'Kansas', 'US'),
('US-KY', 'US', 'Kentucky', 'US'),
('US-LA', 'US', 'Louisiana', 'US'),
('US-ME', 'US', 'Maine', 'US'),
('US-MD', 'US', 'Maryland', 'US'),
('US-MA', 'US', 'Massachusetts', 'US'),
('US-MI', 'US', 'Michigan', 'US'),
('US-MN', 'US', 'Minnesota', 'US'),
('US-MS', 'US', 'Mississippi', 'US'),
('US-MO', 'US', 'Missouri', 'US'),
('US-MT', 'US', 'Montana', 'US'),
('US-NE', 'US', 'Nebraska', 'US'),
('US-NV', 'US', 'Nevada', 'US'),
('US-NH', 'US', 'New Hampshire', 'US'),
('US-NJ', 'US', 'New Jersey', 'US'),
('US-NM', 'US', 'New Mexico', 'US'),
('US-NY', 'US', 'New York', 'US'),
('US-NC', 'US', 'North Carolina', 'US'),
('US-ND', 'US', 'North Dakota', 'US'),
('US-OH', 'US', 'Ohio', 'US'),
('US-OK', 'US', 'Oklahoma', 'US'),
('US-OR', 'US', 'Oregon', 'US'),
('US-PA', 'US', 'Pennsylvania', 'US'),
('US-RI', 'US', 'Rhode Island', 'US'),
('US-SC', 'US', 'South Carolina', 'US'),
('US-SD', 'US', 'South Dakota', 'US'),
('US-TN', 'US', 'Tennessee', 'US'),
('US-TX', 'US', 'Texas', 'US'),
('US-UT', 'US', 'Utah', 'US'),
('US-VT', 'US', 'Vermont', 'US'),
('US-VA', 'US', 'Virginia', 'US'),
('US-WA', 'US', 'Washington', 'US'),
('US-WV', 'US', 'West Virginia', 'US'),
('US-WI', 'US', 'Wisconsin', 'US'),
('US-WY', 'US', 'Wyoming', 'US'),

-- Australia
('AU', 'AU', 'Australia', NULL),
('AU-ACT', 'AU', 'Australian Capital Territory', 'AU'),
('AU-NSW', 'AU', 'New South Wales', 'AU'),
('AU-NT', 'AU', 'Northern Territory', 'AU'),
('AU-QLD', 'AU', 'Queensland', 'AU'),
('AU-SA', 'AU', 'South Australia', 'AU'),
('AU-TAS', 'AU', 'Tasmania', 'AU'),
('AU-VIC', 'AU', 'Victoria', 'AU'),
('AU-WA', 'AU', 'Western Australia', 'AU'),

-- Africa (general regions)
('AF', 'AF', 'África', NULL),
('AF-DZ', 'AF', 'Algeria', 'AF'),
('AF-AO', 'AF', 'Angola', 'AF'),
('AF-BW', 'AF', 'Botswana', 'AF'),
('AF-BF', 'AF', 'Burkina Faso', 'AF'),
('AF-BI', 'AF', 'Burundi', 'AF'),
('AF-CM', 'AF', 'Cameroon', 'AF'),
('AF-CV', 'AF', 'Cape Verde', 'AF'),
('AF-CF', 'AF', 'Central African Republic', 'AF'),
('AF-TD', 'AF', 'Chad', 'AF'),
('AF-KM', 'AF', 'Comoros', 'AF'),
('AF-CG', 'AF', 'Congo', 'AF'),
('AF-CD', 'AF', 'Democratic Republic of Congo', 'AF'),
('AF-DJ', 'AF', 'Djibouti', 'AF'),
('AF-EG', 'AF', 'Egypt', 'AF'),
('AF-GQ', 'AF', 'Equatorial Guinea', 'AF'),
('AF-ER', 'AF', 'Eritrea', 'AF'),
('AF-ET', 'AF', 'Ethiopia', 'AF'),
('AF-GA', 'AF', 'Gabon', 'AF'),
('AF-GM', 'AF', 'Gambia', 'AF'),
('AF-GH', 'AF', 'Ghana', 'AF'),
('AF-GN', 'AF', 'Guinea', 'AF'),
('AF-GW', 'AF', 'Guinea-Bissau', 'AF'),
('AF-CI', 'AF', 'Ivory Coast', 'AF'),
('AF-KE', 'AF', 'Kenya', 'AF'),
('AF-LS', 'AF', 'Lesotho', 'AF'),
('AF-LR', 'AF', 'Liberia', 'AF'),
('AF-LY', 'AF', 'Libya', 'AF'),
('AF-MG', 'AF', 'Madagascar', 'AF'),
('AF-MW', 'AF', 'Malawi', 'AF'),
('AF-ML', 'AF', 'Mali', 'AF'),
('AF-MR', 'AF', 'Mauritania', 'AF'),
('AF-MU', 'AF', 'Mauritius', 'AF'),
('AF-MA', 'AF', 'Morocco', 'AF'),
('AF-MZ', 'AF', 'Mozambique', 'AF'),
('AF-NA', 'AF', 'Namibia', 'AF'),
('AF-NE', 'AF', 'Niger', 'AF'),
('AF-NG', 'AF', 'Nigeria', 'AF'),
('AF-RW', 'AF', 'Rwanda', 'AF'),
('AF-ST', 'AF', 'São Tomé and Príncipe', 'AF'),
('AF-SN', 'AF', 'Senegal', 'AF'),
('AF-SC', 'AF', 'Seychelles', 'AF'),
('AF-SL', 'AF', 'Sierra Leone', 'AF'),
('AF-SO', 'AF', 'Somalia', 'AF'),
('AF-ZA', 'AF', 'South Africa', 'AF'),
('AF-SS', 'AF', 'South Sudan', 'AF'),
('AF-SD', 'AF', 'Sudan', 'AF'),
('AF-SZ', 'AF', 'Eswatini', 'AF'),
('AF-TZ', 'AF', 'Tanzania', 'AF'),
('AF-TG', 'AF', 'Togo', 'AF'),
('AF-TN', 'AF', 'Tunisia', 'AF'),
('AF-UG', 'AF', 'Uganda', 'AF'),
('AF-ZM', 'AF', 'Zambia', 'AF'),
('AF-ZW', 'AF', 'Zimbabwe', 'AF'),

-- Europe (general regions)
('EU', 'EU', 'Europa', NULL),
('EU-AL', 'EU', 'Albania', 'EU'),
('EU-AD', 'EU', 'Andorra', 'EU'),
('EU-AT', 'EU', 'Austria', 'EU'),
('EU-BY', 'EU', 'Belarus', 'EU'),
('EU-BE', 'EU', 'Belgium', 'EU'),
('EU-BA', 'EU', 'Bosnia and Herzegovina', 'EU'),
('EU-BG', 'EU', 'Bulgaria', 'EU'),
('EU-HR', 'EU', 'Croatia', 'EU'),
('EU-CY', 'EU', 'Cyprus', 'EU'),
('EU-CZ', 'EU', 'Czech Republic', 'EU'),
('EU-DK', 'EU', 'Denmark', 'EU'),
('EU-EE', 'EU', 'Estonia', 'EU'),
('EU-FI', 'EU', 'Finland', 'EU'),
('EU-FR', 'EU', 'France', 'EU'),
('EU-GE', 'EU', 'Georgia', 'EU'),
('EU-DE', 'EU', 'Germany', 'EU'),
('EU-GR', 'EU', 'Greece', 'EU'),
('EU-HU', 'EU', 'Hungary', 'EU'),
('EU-IS', 'EU', 'Iceland', 'EU'),
('EU-IE', 'EU', 'Ireland', 'EU'),
('EU-IT', 'EU', 'Italy', 'EU'),
('EU-XK', 'EU', 'Kosovo', 'EU'),
('EU-LV', 'EU', 'Latvia', 'EU'),
('EU-LI', 'EU', 'Liechtenstein', 'EU'),
('EU-LT', 'EU', 'Lithuania', 'EU'),
('EU-LU', 'EU', 'Luxembourg', 'EU'),
('EU-MT', 'EU', 'Malta', 'EU'),
('EU-MD', 'EU', 'Moldova', 'EU'),
('EU-MC', 'EU', 'Monaco', 'EU'),
('EU-ME', 'EU', 'Montenegro', 'EU'),
('EU-NL', 'EU', 'Netherlands', 'EU'),
('EU-MK', 'EU', 'North Macedonia', 'EU'),
('EU-NO', 'EU', 'Norway', 'EU'),
('EU-PL', 'EU', 'Poland', 'EU'),
('EU-PT', 'EU', 'Portugal', 'EU'),
('EU-RO', 'EU', 'Romania', 'EU'),
('EU-RU', 'EU', 'Russia', 'EU'),
('EU-SM', 'EU', 'San Marino', 'EU'),
('EU-RS', 'EU', 'Serbia', 'EU'),
('EU-SK', 'EU', 'Slovakia', 'EU'),
('EU-SI', 'EU', 'Slovenia', 'EU'),
('EU-ES', 'EU', 'Spain', 'EU'),
('EU-SE', 'EU', 'Sweden', 'EU'),
('EU-CH', 'EU', 'Switzerland', 'EU'),
('EU-TR', 'EU', 'Turkey', 'EU'),
('EU-UA', 'EU', 'Ukraine', 'EU'),
('EU-GB', 'EU', 'United Kingdom', 'EU'),
('EU-VA', 'EU', 'Vatican City', 'EU')

ON CONFLICT (code) DO NOTHING;